### ISSUE TITLE
Login is not working.

### ISSUE THREAD

**Issue by mohammadusman** [forddyce/mlm-3#1]
Is there any other config need to do?

**Comment by forddyce** [comment]
Change your vendor/cartalyst/sentinel/src/Users/EloquentUser.php to this: https://github.com/forddyce/mlm-2/blob/master/EloquentUser.php

**Comment by mohammadusman** [comment]
Thanks for quick reply, now it is saying User is not a member, I am using the following credentials.
Username: admin
Password: password

**Comment by mohammadusman** [comment]
@forddyce any help will be appreciated. 

Thanks!

**Comment by forddyce** [comment]
have you run the seeder? Did your database already have admin?

**Comment by mohammadusman** [comment]
Yes, I ran seeder and DB have admin!

**Comment by forddyce** [comment]
then you logged in to the wrong link, you have to login from /admin

**Comment by mohammadusman** [comment]
Thanks, @forddyce!
